[package]
name = "telecord"
version = "0.1.0"
authors = ["Riley Trautman <asonix@tamu.edu>"]

[dependencies]
dotenv = "0.10"
serenity = "0.4.3"
mime = "0.3"
mime-sniffer = "0.1"
telebot = "0.2.1"
lazy_static = "0.2"
tokio-core = "0.1"
futures = "0.1"
